### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by JaceHensley** [hellobloom/ssi-sdk#6]
We need better documentation for all the libraries in this repo.

Acceptance Criteria:
- Top level `docs/` folder
  - Single [docusaurus](https://docusaurus.io/) instance that has a folder for each library
- Publish to [GitHub pages](https://v1.docusaurus.io/docs/en/publishing#using-github-pages), using a GitHub action like:
```yml
name: build docs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build Docs
        run: |
          cd docs
          npm i
          npm run docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          allow_empty_commit: true
          force_orphan: true

```
